services:
  client:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./client:/usr/share/nginx/html:ro
    networks:
      - app-network

  database: 
    image: mysql:8.4
    restart: always
    ports: 
        - "3307:3306"
        - "33061:33060"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      
    

  api:
    build: ./api
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./api:/app
    command: node index.js

networks:
  app-network:
