name: run all tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with: 
          version: lastest

      - name: test e2e
        run: npm run e2e

      - name: run unit test on api
        run: docker compose exec api-1 exec run test

      - name: run lint on api
        run: docker compose exec api-1 exec run lint